### ISSUE TITLE
Toml Ambiguities

### ISSUE THREAD

**Issue by bd82** [bd82/toml-tools#12]
- Float in key
  ```toml
  [95.22.looks.like.a.float]
  name = "John"
  ```

- "[[" vs "[" (Table of Arrays vs Array vs Table vs array with first element another array)
  ```toml
     [[Table.of.arrays]]
     # Array value with first item being a nested array
     items = [[1,2,3], [4,5,6]]

  ```
