### ISSUE TITLE
prettier-plugin-toml cannot ignore lines

### ISSUE THREAD

**Issue by Horstage** [bd82/toml-tools#79]
In the [Prettier Docs](https://prettier.io/docs/en/ignore) it is a general rule to put `# prettier-ignore` before the token to be ignored.
This does not work with this plugin.

## Input
```toml
[example]
# prettier-ignore
foo = [
    "bar",
    "baz",
]
hello = [
    "world"
]
```

## Expected Output
```toml
[example]
# prettier-ignore
foo = [
    "bar",
    "baz",
]
hello = ["world"]
```

## Actual Output
```toml
[example]
# prettier-ignore
foo = ["bar", "baz"]
hello = ["world"]
```

## Workaround
```toml
[example]
foo = [  # prettier-ignore, but any comment does the trick
    "bar",
    "baz",
]
hello = ["world"]
```
