### ISSUE TITLE
prettier-plugin-toml Feature Request: Magic Trailing Comma

### ISSUE THREAD

**Issue by Horstage** [bd82/toml-tools#80]
In Python I got used to the [Magic Trailing Comma](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#the-magic-trailing-comma) which prevents collapsing a list into one line, if there is a trailing comma in the last element.
> There are cases where you put a short collection or function call in your code but you anticipate it will grow in the future.

## Input
```toml
[example]
foo = [
    "bar",
    "baz",
]
hello = [
    "world"
]
```

## Expected output
```toml
[example]
foo = [
    "bar",
    "baz",
]
hello = ["world"]
```
