### ISSUE TITLE
Prettier formatting not working

### ISSUE THREAD

**Issue by aryzing** [bd82/toml-tools#81]
Multiline objects aren't formatted properly. E.g, the following will fail to format:

```toml
[install.scopes]

"@myorg2" = { 
  username = "myusername", 
  password = "$NPM_PASS", 
  url = "https://registry.myorg.com/" 
}
```
